name: "@iwsio/fetch: PUSH to main"

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/fetch/**'

jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v2
    with:
      registry-url: 'https://registry.npmjs.org'
      scope: '@iwsio'
      cache: npm
      node-version-file: '.nvmrc'
      install-command: npm ci
      test-command: npm run test -w packages/fetch
  version:
    needs: tests
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/version.yaml@v2
    with:
      ref: main
      registry-url: 'https://registry.npmjs.org'
      node-version-file: '.nvmrc'
      cache: npm
      scope: '@iwsio'
      version-command: npm version patch -w packages/fetch
      version-workspace: packages/fetch
      tag-includes-name: true
  publish:
    needs: version
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/publish.yaml@v2
    with:
      ref: main
      registry-url: 'https://registry.npmjs.org'
      cache: npm
      node-version-file: '.nvmrc'
      scope: '@iwsio'
      install-command: npm ci
      build-command: npm run build -w packages/fetch
      publish-command: npm publish -w packages/fetch --access public
    secrets:
      # This token is used for reading npm packages; use when private packages are used
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
